[tool.poetry]
name = "projeto-modern-data-stack"
version = "0.1.0"
description = ""
authors = ["tiagojbandrade <tiagobarbosajp@yahoo.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "==3.11.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
